name: Build and Publish

on:
  push:
    branches:
      - master
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Build with Maven
        run: mvn clean install

      - name: Deploy to GitHub Packages
        run: |
          mvn deploy -DskipTests -Dmaven.repo.local=repo -DaltDeploymentRepository=github::default::https://maven.pkg.github.com/ythrinathareddy/ythrinathreddy/devops
        env:
          MAVEN_USERNAME: ${{ github.ythrinathareddy }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_GITHUB_TOKEN }}

      - name: Verify Published Package
        run: |
          mvn dependency:get -DgroupId=First_project -DartifactId=Maven_First_Project_Demo -Dversion=1.0-SNAPSHOT -Dpackaging=jar -DremoteRepositories=https://maven.pkg.github.com/ythrinathareddy/ythrinathreddy/devops
