name: Build and Publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Build with Maven
        run: mvn clean install

      - name: Deploy to GitHub Packages
        run: |
          mvn deploy -DskipTests -Dmaven.repo.local=repo -DaltDeploymentRepository=github::default::https://maven.pkg.github.com/OWNER/REPO
        env:
          MAVEN_USERNAME: ${{ github.actor }}
          MAVEN_PASSWORD: ${{ secrets.APP_TOKEN }}

      - name: Verify Published Package
        run: |
          mvn dependency:get -DgroupId=group -DartifactId=artifact -Dversion=version -Dclassifier=classifier -Dpackaging=jar -DremoteRepositories=https://maven.pkg.github.com/OWNER/REPO
